---
repos:
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.2.1   # or other specific tag
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0', --colons, --width, '150']

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0  # Use the ref you want to point at
  hooks:
  - id: check-yaml
