---
name: Build NodeJS Binary

on:
  workflow_call:
    inputs:
      SOURCE:
        description: 项目源码地址
        required: true
        type: string
      VERSION:
        description: 构建版本号（可选，默认最新）
        required: false
        type: string
      BUILD_DIR:
        description: 构建目录（可选，默认项目根目录）
        required: false
        type: string
      EXTRA_ARGS:
        description: 扩展参数（可选，默认无）
        required: false
        type: string

jobs:
  build:
    # if: false
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Set env
      run: |
        echo "SOURCE=${{ github.event.inputs.SOURCE }}" >> $GITHUB_ENV
        echo "VERSION=${{ github.event.inputs.VERSION }}" >> $GITHUB_ENV
        echo "BUILD_DIR=${{ github.event.inputs.BUILD_DIR }}" >> $GITHUB_ENV
        echo "EXTRA_ARGS=${{ github.event.inputs.EXTRA_ARGS }}" >> $GITHUB_ENV
        PROJECT_NAME=$(basename "${{ github.event.inputs.SOURCE }}" .git)
        echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
    - name: Checkout source code
      run: |
        git clone "${{ env.SOURCE }}" repo
        cd repo
        if [ -n "${{ env.VERSION }}" ]; then
          git checkout "${{ env.VERSION }}"
        fi   
    - name: Get project name
      run: |
        PACKAGE_FILE=$(find ./repo -type f -name 'package.json' | head -n 1)
        if [ -z "$PACKAGE_FILE" ]; then
          echo "package.json not found"
          exit 1
        fi
        PROJECT_NAME=$(node -p "require('$PACKAGE_FILE').name")
        if [ -n "$PROJECT_NAME" ]; then
          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
        fi
        if [ -z "${{ env.BUILD_DIR }}" ]; then
          BUILD_DIR=$(dirname "$PACKAGE_FILE")
          echo "BUILD_DIR=$BUILD_DIR" >> $GITHUB_ENV
        fi
    - name: Create Tag
      run: |
        if [ -n "${{ env.VERSION }}" ]; then
          TAG_NAME="${{ env.PROJECT_NAME }}-${{ env.VERSION }}"
        else
          TAG_NAME="${{ env.PROJECT_NAME }}-$(date +%Y%m%d)"
        fi
        git tag "$TAG_NAME"
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

    - name: Build
      working-directory: ./repo
      run: |
        npm install
        npm run build
    - name: Compress
      run: |
        mv repo/dist "${{ env.PROJECT_NAME }}"
        tar -zcvf "${{ env.PROJECT_NAME }}.tar.gz" "${{ env.PROJECT_NAME }}"

    - name: Get short hash
      working-directory: ./repo
      run: |
        GIT_REV=$(git rev-parse --short HEAD)
        echo "GIT_REV=$GIT_REV" >> $GITHUB_ENV
        SOURCE_URL=${{ env.SOURCE }}
        echo "SOURCE_CODE_URL=${SOURCE_URL%.git}/tree/${GIT_REV}" >> $GITHUB_ENV
        echo "SOURCE_GIT_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV
    - name: Upload Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.TAG_NAME }}
        files: ${{ env.PROJECT_NAME }}.tar.gz
        body: |
          Date: ${{ env.SOURCE_GIT_DATE }}
          Platform: **NodeJS**
          Source: [${{ env.SOURCE }}](${{ env.SOURCE_CODE_URL }})
          Publish by [Jetsung Chan](https://github.com/jetsung)
        append_body: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
